apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-volume
  labels:
    type: local
spec:
  storageClassName: manual
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: "192.168.100.10"
    path: "/srv/nfs/data"
